#define	SHOOTER_SHOOT	
#define DRIVE_SET_BRAKES_ON	4
#define DRIVE_SET_BRAKES_OFF	5

#define SET_SHOOTER_SPEED_MEDIUM	9
#define SET_SHOOTER_SPEED_FAR		11

#define BRIDGE	2

#define BALL_PICKUP	4
#define BALL_FEEDER	3

#define GET_LEFT_ENCODER	8
#define GET_RIGHT_ENDOCER	9

#define PERFORM_BALANCE_TRICK	1
